[package]
name = "server"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
arrow = { version = "6.0", features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
bytes = "1.0"
chrono = { version = "0.4", default-features = false }
cache_loader_async = { version = "0.1.2", features = ["ttl-cache"] }
crc32fast = "1.3.0"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
dml = { path = "../dml" }
futures = "0.3"
futures-util = { version = "0.3" }
generated_types = { path = "../generated_types", features = ["data_types_conversions"] }
hashbrown = "0.11"
influxdb_iox_client = { path = "../influxdb_iox_client" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
internal_types = { path = "../internal_types" }
iox_object_store = { path = "../iox_object_store" }
itertools = "0.10.1"
lifecycle = { path = "../lifecycle" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
mutable_buffer = { path = "../mutable_buffer" }
num_cpus = "1.13.0"
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.4.0", features = ["parking_lot"] }
parking_lot = "0.11.2"
parquet_catalog = { path = "../parquet_catalog" }
parquet_file = { path = "../parquet_file" }
persistence_windows = { path = "../persistence_windows" }
predicate = { path = "../predicate" }
query = { path = "../query" }
rand = "0.8.3"
rand_distr = "0.4.2"
read_buffer = { path = "../read_buffer" }
schema = { path = "../schema" }
serde = "1.0"
serde_json = "1.0"
snafu = "0.6"
snap = "1.0.0"
time = { path = "../time" }
trace = { path = "../trace" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.6.9" }
tracker = { path = "../tracker" }
uuid = { version = "0.8", features = ["v4"] }
write_buffer = { path = "../write_buffer" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
regex = "1"
router = { path = "../router" }
test_helpers = { path = "../test_helpers" }

[features]
default = []

# Enable features for benchmarking
bench = ["mutable_buffer/nocache"]

kafka = ["write_buffer/kafka"]
